app/__init__.py
import os
from flask_sqlalchemy import SQLAlchemy
from config import config
from flask_login import LoginManager,current_user
from flask import Flask,redirect,url_for,render_template,request,current_app
from flask_mail import Mail
from datetime import datetime
import jwt

#initialize packages used in the application
db = SQLAlchemy()
mail = Mail()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
#login_manager.login_view = 'index'

#create an initialation of the application
def create_app(config_name):
    # Define the WSGI application object
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    # Define the database and login manager object which is imported
    # by modules and controllers
    db.init_app(app)
    mail.init_app(app)
    login_manager.init_app(app)

    #Define index for homepage or landing page for visitors
    @app.route('/')
    def index():
        return render_template('index.html')

    #registering admin blueprint for ease of usage
    from .admin import admin as admin_blueprint
    app.register_blueprint(admin_blueprint, url_prefix='/admin')

    # registering creatives blueprint for ease of usage
    from .creatives import creatives as creatives_blueprint
    app.register_blueprint(creatives_blueprint, url_prefix='/creatives')

    return (app)

app/admin/__init__.py
from flask import  Blueprint

admin = Blueprint('admin',__name__)

from . import views

app/admin/views.py
from . import admin
from ..model import Skill,Creatives,db
from flask import request,render_template,redirect,url_for
from .mail import send_activation
from .. import current_app
import jwt


#Creating registering route for new users
@admin.route('/register',methods=['GET','POST'])
def registeration():
    #getting every skill from database to display in the registeration tab
    skills = Skill.query.all()
    if request.method == "POST":
        email = request.form["email"]
        instagram_name = request.form["instagram_username"]
        creative_email = Creatives.query.filter_by(email=email).first()
        creative_insta = Creatives.query.filter_by(instagram_account =instagram_name).first()
        if creative_email or creative_insta:
            db.session.rollback()
            return redirect(url_for("admin.registeration"))
        creative = Creatives(
            name= request.form["name"],
            password_hash = request.form["name"],
            email = request.form["email"],
            active = "No",
            instagram_account = request.form["instagram_username"],
            #skill = request.form[""]
        )

        print(12345)
        skills = request.form.getlist('skills')
        for skill in skills:
            creative.skill.append(Skill.query.get(skill))
        db.session.add(creative)
        db.session.commit()
    return render_template("index.html",skill = skills)

"""@admin.route('/login',methods=['GET','POST'])
def login():
    return render_template("")"""

@admin.route('/admin-dashboard')
def admindashboard():

    return render_template("admin-dashboard.html")

@admin.route('/create-task',methods=['GET','POST'])
def createtask():
    
    return render_template("create_task.html")

@admin.route('/view-attendee')
def view_attendee():
    return render_template("view_attendee.html")

@admin.route('/add-winner')
def add_winner():
    return render_template("add winner.html")

@admin.route('/about-platform')
def about_platform():
    return render_template("about.html")


#Creatives are accepted and a mail is sent to them for their approval
@admin.route('/accept-new-creatives',methods=["GET","POST"])
def accept_new_creatives():
    creatives = Creatives.query.filter_by(active = "No")
    return render_template("add_creatives.html",creatives = creatives)

@admin.route('/accept/<int:id>')
def accept(id):
    creative = Creatives.query.filter_by(id=id).first()
    send_activation(creative)
    return redirect(url_for('admin.accept_new_creatives'))

@admin.route('/activate/<token>')
def activate(token):
    creative = Creatives.verify_accept_token(token)
    if not creative:
        return redirect(url_for('admin.registeration'))
    creative.active = "Yes"
    db.session.commit()
    return redirect(url_for('admin.accept_new_creatives'))

@admin.route('/add-skills',methods=['GET','POST'])
def add_category():
    skilled = Skill.query.all()
    if request.method == 'POST':
        skilli = Skill(
            skills = request.form['skill']
        )
        db.session.add(skilli)
        db.session.commit()
        return redirect(url_for("admin.add_category"))
    return render_template('add_category.html',skill = skilled)

@admin.route('/delete-skill/<int:id>')
def delete_category(id):
    Skill.query.filter_by(id = id).delete()
    db.session.commit()
    return redirect(url_for('admin.add_category'))

app/creatives/__init__.py
from flask import  Blueprint

creatives = Blueprint('creative',__name__)

from . import views

app/creatives/views.py
from . import creatives
from ..model import Skill,Creatives,db
from flask import request,render_template,redirect,url_for


@creatives.route('/index')
def creative():
    return  render_template('about.html')

@creatives.route('/accepttask')
def accept_task():
    return  render_template('accept_task.html')

@creatives.route('/submit-task')
def submit_task():
    return  render_template('submit_task.html')

@creatives.route('/view_profile')
def view_profile():
    return  render_template('view_profile.html')

app/templates/about.html
{% extends "layout.html" %}

app/templates/add winner.html
{% extends "layout.html" %}

app/templates/add_category.html
{% extends "layout.html" %}

{% block body %}
<div class="col-lg-6">
    <div class="box-quote bg-gray-100">
            <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Skill</th>
                        <th>   </th>
                        
                      </tr>
                    </thead>
                    {% for skill in skill  %}
                    <tbody>
                      <tr>
                        <td>{{ skill.skills }}</td>
                        <td><a href="{{ url_for('admin.delete_category', id=skill.id) }}">Delete</a></td>
                      </tr>
                    </tbody>
                    {% endfor %}
                </table>
    </div>
</div>
<form action="{{url_for('admin.add_category')}}" method="Post">
    <div class="col-lg-6">
        <div class="box-quote bg-gray-100">
            <div class="form-wrap">
                <input class="form-input" id="contact-name" type="text" name="skill"
                    data-constraints="@Required">
                <label class="form-label" for="contact-name">Add new Category/Skills:</label>
            </div>
        </div>
        <button class="button button-block button-secondary button-lg" type="submit">SUBMIT</button>
    </div>
</form>
{% endblock %}

app/templates/add_creatives.html
{% extends "layout.html" %}

{% block body %}

<section class="section section-lg bg-gray-100">
    <div class="container">
        <table class="table table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Instagram name </th>
                <th>Status</th>
              </tr>
            </thead>
            {% for creative in creatives  %}
            <tbody>
              <tr>
                <td>{{ creative.name }}</td>
                <td>{{ creative.email }}</td>
                <td>{{ creative.instagram_account }}</td>
                <td>{{ creative.active }}</td>
                <td><a href="{{ url_for('admin.accept',id = creative.id) }}"><span class="label label-primary">Accept</span></a></td>
              </tr>
            </tbody>
            {% endfor %}
        </table>
    </div>
</section>

{% endblock %}

app/templates/admin-dashboard.html
{% extends "layout.html" %}

{% block body %}
       <!-- Services-->
      <section class="section section-lg bg-gray-100">
        <div class="container">
          <div class="row row-30">
            <div class="col-xl-4 col-md-6">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title">Create Task</h5>
                      <p class="card-text">Create task for select Creatives to handle</p>
                      <a href="#" class="card-link">Card link</a>
                    </div>
                  </div>
            </div>
            <div class="col-xl-4 col-md-6">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title">View Attendee</h5>
                      <p class="card-text">See those who accepted a task given to them to handle</p>
                      <a href="#" class="card-link">Card link</a>
                      <a href="#" class="card-link">Another link</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-md-6">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title">Add Winner</h5>
                      <p class="card-text">Add The selected winner to a competion</p>
                      <a href="#" class="card-link">Card link</a>
                      <a href="#" class="card-link">Another link</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-md-6">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title">Add Category</h5>
                      <p class="card-text">Add new skill set to the platform</p>
                      <a href="#" class="card-link">Card link</a>
                      <a href="#" class="card-link">Another link</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-md-6">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title">Write About the platform</h5>
                      <p class="card-text">Talk about the platform </p>
                      <a href="#" class="card-link">Card link</a>
                      <a href="#" class="card-link">Another link</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-md-6">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title">Accept new creatives</h5>
                      <p class="card-text">Accept new creatives onto the platform</p>
                      <a href="#" class="card-link">Card link</a>
                      <a href="#" class="card-link">Another link</a>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

{% endblock %}

app/templates/create_task.html
{% extends "layout.html" %}

{% block body %}
<section class="section section-md bg-gray-600 pb-lg-0">
    <div class="container">
        <div class="row row-50">
            <div class="col-lg-6">
                <h2 class="mt-lg-26">Create cute websites</h2>
                <h1>fast with us!</h1>
                <ul class="list-marked-modern pr-xl-5">
                    <li>
                        <div class="unit unit-spacing-xs">
                            <div class="unit-left">
                                <div class="icon novi-icon icon-lg text-primary flaticon-check64"></div>
                            </div>
                            <div class="unit-body">
                                <h4 class="text-primary">Designed by industry professionals</h4>
                                <p>Every website we designed and developed for our numerous customers is backed by over
                                    20 years of
                                    experience our team has.</p>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="unit unit-spacing-xs">
                            <div class="unit-left">
                                <div class="icon novi-icon icon-lg text-primary flaticon-check64"></div>
                            </div>
                            <div class="unit-body">
                                <h4 class="text-primary">Fully responsive</h4>
                                <p>At Wrico, we design and develop highly responsive and reliable websites for the needs
                                    of our
                                    clients and partners.</p>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="unit unit-spacing-xs">
                            <div class="unit-left">
                                <div class="icon novi-icon icon-lg text-primary flaticon-check64"></div>
                            </div>
                            <div class="unit-body">
                                <h4 class="text-primary">Designed to sell</h4>
                                <p>We guarantee every website we create for you will improve your company’s image and
                                    increase the
                                    conversion rate.</p>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="col-lg-6">
                <div class="box-quote bg-gray-100">
                    <h3>Request a quote now!</h3>
                    <p>If you need a high-quality website, feel free to select one of desired solutions and request a
                        quote
                        using the form below.</p>
                    <form class="rd-form rd-mailform" data-form-output="form-output-global" data-form-type="contact"
                        method="post" action="{{url_for('admin.registeration')}}">
                        <div class="form-wrap">
                            <input class="form-input" id="contact-name" type="text" name="name"
                                data-constraints="@Required">
                            <label class="form-label" for="contact-name">Name:</label>
                        </div>
                        <div class="form-wrap">
                            <input class="form-input" id="contact-name" type="text" name="instagram_username"
                                data-constraints="@Required">
                            <label class="form-label" for="contact-name">Instagram Username:</label>
                        </div>
                        <div class="form-wrap">
                            <input class="form-input" id="contact-email" type="email" name="email"
                                data-constraints="@Email @Required">
                            <label class="form-label" for="contact-email">E-mail:</label>
                        </div>
                        <div class="form-wrap">
                            <!-- Select 2-->
                            <select multiple class="form-input select" data-placeholder="Select Skill"
                                data-constraints="@Required">
                                <option label="placeholder"></option>
                                <option value="2">Make up</option>
                                <option value="3">PhotoGraphy</option>
                                <option value="4">Web Development</option>
                                <option value="5">UX Research</option>
                            </select>
                        </div>
                        <button class="button button-block button-secondary button-lg" type="submit">Get a
                            quote!</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/dashboard.html
<!DOCTYPE html>
<html class="wide wow-animation" lang="en">
  <head>
    <title>Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu:300,400,500,700">
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/fonts.css">
    <link rel="stylesheet" href="css/style.css">
    <style>.ie-panel{display: none;background: #212121;padding: 10px 0;box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3);clear: both;text-align:center;position: relative;z-index: 1;} html.ie-10 .ie-panel, html.lt-ie-10 .ie-panel {display: block;}</style>
  </head>
  <body>
    <div class="ie-panel"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img src="images/ie8-panel/warning_bar_0000_us.jpg" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <div class="preloader">
      <div class="preloader-body">
        <div class="cssload-container">
          <div class="cssload-speeding-wheel"></div>
        </div>
      </div>
    </div>
    <div class="page">
      <header class="section page-header">
        <!--Brand--><a class="brand" href="index.html"><img src="images/logo-default-228x64.png" alt="" width="114" height="32"/>Web design studio</a>
      </header>
      
      <!-- Services-->
      <section class="section section-lg bg-gray-100">
        <div class="container">
          <div class="row row-30">
            <div class="col-xl-4 col-md-6">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title">Create Task</h5>
                      <p class="card-text">Create task for select Creatives to handle</p>
                      <a href="#" class="card-link">Card link</a>
                    </div>
                  </div>
            </div>
            <div class="col-xl-4 col-md-6">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title">View Attendee</h5>
                      <p class="card-text">See those who accepted a task given to them to handle</p>
                      <a href="#" class="card-link">Card link</a>
                      <a href="#" class="card-link">Another link</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-md-6">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title">Add Winner</h5>
                      <p class="card-text">Add The selected winner to a competion</p>
                      <a href="#" class="card-link">Card link</a>
                      <a href="#" class="card-link">Another link</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-md-6">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title">Add Category</h5>
                      <p class="card-text">Add new skill set to the platform</p>
                      <a href="#" class="card-link">Card link</a>
                      <a href="#" class="card-link">Another link</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-md-6">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title">Write About the platform</h5>
                      <p class="card-text">Talk about the platform </p>
                      <a href="#" class="card-link">Card link</a>
                      <a href="#" class="card-link">Another link</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-md-6">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title">Accept new creatives</h5>
                      <p class="card-text">Accept new creatives onto the platform</p>
                      <a href="#" class="card-link">Card link</a>
                      <a href="#" class="card-link">Another link</a>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <footer class="section footer-classic context-dark">
        <div class="container">
          <p class="rights">
            <!--Brand--><a class="brand" href="index.html"><img src="images/logo-default-228x64.png" alt="" width="114" height="32"/></a><span>&copy;&nbsp;</span><span class="copyright-year"></span><span>&nbsp;</span><span>. All Rights Reserved</span>. Design&nbsp;by&nbsp;<a href="https://zemez.io/">Zemez</a>
          </p>
        </div>
      </footer>
    </div>
    <div class="snackbars" id="form-output-global"></div>
    <script src="js/core.min.js"></script>
    <script src="js/script.js"></script>
    <!-- coded by kraken-->
  </body>
</html>

app/templates/layout.html
<!DOCTYPE html>
<html class="wide wow-animation" lang="en">

<head>
  <title>Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="icon" href="images/favicon.ico" type="image/x-icon">
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu:300,400,500,700">
  <link rel="stylesheet" href="static/css/bootstrap.css">
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/css/fonts.css">
  <link rel="stylesheet" href="/static/css/style.css">
  <style>
    .ie-panel {
      display: none;
      background: #212121;
      padding: 10px 0;
      box-shadow: 3px 3px 5px 0 rgba(0, 0, 0, .3);
      clear: both;
      text-align: center;
      position: relative;
      z-index: 1;
    }

    html.ie-10 .ie-panel,
    html.lt-ie-10 .ie-panel {
      display: block;
    }
  </style>
</head>

<body>
  <div class="ie-panel"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img
        src="images/ie8-panel/warning_bar_0000_us.jpg" height="42" width="820"
        alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a>
  </div>
  <div class="preloader">
    <div class="preloader-body">
      <div class="cssload-container">
        <div class="cssload-speeding-wheel"></div>
      </div>
    </div>
  </div>
  <div class="page">
    <header class="section page-header">
      <nav>
        <!--Brand--><a class="brand" href="index.html"><img src="images/logo-default-228x64.png" alt="" width="12"
            height="12" />Web design studio</a>
        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>

            <!-- Dropdown -->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">Dropdown</a>
              <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>

          </ul>
        </div>
      </nav>
    </header>
    {% block body %}
    
    {% endblock %}
    <footer class="section footer-classic context-dark">
      <div class="container">
        <p class="rights">
          <!--Brand--><a class="brand" href="index.html"><img src="images/logo-default-228x64.png" alt="" width="114"
              height="32" /></a><span>&copy;&nbsp;</span><span class="copyright-year"></span><span>&nbsp;</span><span>.
            All Rights Reserved</span>. Design&nbsp;by&nbsp;<a href="https://zemez.io/">Zemez</a>
        </p>
      </div>
    </footer>
  </div>
  <div class="snackbars" id="form-output-global"></div>
  <script src="/static/js/core.min.js"></script>
  <script src="/static/js/script.js"></script>
  <!-- coded by kraken-->
</body>

</html>

app/templates/view_attendee.html
{% extends "layout.html" %}